const fs = require('fs-extra');
const path = require('path');
const https = require('https');
const archiver = require('archiver');

// Pinata configuration
const PINATA_CONFIG = {
    apiKey: '3e5fb97332d629f94989',
    secretKey: '1ddb40666bc3eba58924b92094f85fac46ab58d3fba56f0a4e17e192dc7393b7'
};

// Brick image URLs (already on IPFS)
const BRICK_IMAGES = {
    regular: 'https://gateway.pinata.cloud/ipfs/bafkreigqsyyi6qumiq544of4kzwfgffohvnvq36usivstvrfyw52u5qxf4',
    industrial: 'https://gateway.pinata.cloud/ipfs/bafkreiav6vreyevxu5l7c43ze64oaopgvsi23xx6jfmg4zjlytfqppvtka',
    legendary: 'https://gateway.pinata.cloud/ipfs/bafkreibhok44eomzkubmt3e2kzxip3w3b4pclixvgff5g7awhfa7kwlwsq'
};

// Function to determine brick type from brick ID
function getBrickType(brickId) {
    if (brickId >= 422 && brickId <= 432) return 'legendary';
    if (brickId >= 362 && brickId <= 421) return 'industrial';
    return 'regular'; // 1-361
}

// Function to create zip file
async function createMetaBricksZip() {
    return new Promise((resolve, reject) => {
        const zipPath = path.join(__dirname, 'metabricks-collection.zip');
        const output = fs.createWriteStream(zipPath);
        const archive = archiver('zip', {
            zlib: { level: 9 } // Maximum compression
        });
        
        output.on('close', () => {
            console.log(`✅ ZIP file created: ${zipPath}`);
            console.log(`📏 Total size: ${(archive.pointer() / 1024 / 1024).toFixed(2)} MB`);
            resolve(zipPath);
        });
        
        archive.on('error', (err) => {
            reject(err);
        });
        
        archive.pipe(output);
        
        // Get randomized metadata directory
        const metadataDir = path.join(__dirname, 'pinata-upload-randomized');
        
        // Add all JSON files to zip
        const jsonFiles = fs.readdirSync(metadataDir)
            .filter(file => file.endsWith('.json'))
            .sort((a, b) => {
                const numA = parseInt(a.replace('.json', ''));
                const numB = parseInt(b.replace('.json', ''));
                return numA - numB;
            });
        
        let processedCount = 0;
        
        jsonFiles.forEach(file => {
            try {
                const filePath = path.join(metadataDir, file);
                const content = fs.readFileSync(filePath, 'utf8');
                const metadata = JSON.parse(content);
                
                // Extract the original brick ID from the name
                const nameMatch = metadata.name && metadata.name.match(/MetaBrick #(\d+)/);
                if (nameMatch) {
                    const originalBrickId = parseInt(nameMatch[1]);
                    const brickType = getBrickType(originalBrickId);
                    
                    // Update the image URL to use the correct brick type
                    metadata.image = BRICK_IMAGES[brickType];
                    
                    // Add upload metadata
                    metadata.uploadNumber = parseInt(file.replace('.json', ''));
                    metadata.originalBrickId = originalBrickId;
                    metadata.brickType = brickType;
                    metadata.uploadTimestamp = new Date().toISOString();
                    
                    // Add to zip
                    archive.append(JSON.stringify(metadata, null, 2), { name: file });
                    processedCount++;
                } else {
                    console.log(`   ⚠️ Skipping ${file}: Invalid name format`);
                }
            } catch (error) {
                console.log(`   ❌ Error processing ${file}: ${error.message}`);
            }
        });
        
        console.log(`   ✅ Processed ${processedCount} valid metadata files`);
        
        // Add README file
        const readmeContent = `# MetaBricks Collection

This archive contains all 432 MetaBricks metadata files organized in randomized order for the mystery strategy.

## Collection Details
- Total Files: 432
- Strategy: Randomized Mystery
- Upload Date: ${new Date().toISOString()}
- Collection: MetaBricks

## File Structure
- Files are numbered 1-432 in randomized order
- Each file contains metadata for a specific MetaBrick
- Image URLs are correctly linked to the appropriate brick type
- TGE discounts are set by brick rarity (10%/15%/20%)

## Usage
Extract this ZIP file to access individual metadata JSON files.
Each file can be used for NFT minting with the mystery strategy.

## Mystery Strategy
Buyers see MetaBrick #1, #2, #3, etc., but don't know the actual rarity until they purchase.
This creates excitement and prevents rarity sniping.

## Brick Types
- Regular Bricks (1-361): 10% TGE discount
- Industrial Bricks (362-421): 15% TGE discount  
- Legendary Bricks (422-432): 20% TGE discount

Generated by MetaBricks Upload Script
`;
        
        archive.append(readmeContent, { name: 'README.md' });
        
        // Add collection info
        const collectionInfo = {
            name: 'MetaBricks Collection',
            description: 'Complete MetaBricks NFT collection with randomized mystery strategy',
            totalFiles: 432,
            strategy: 'Randomized Mystery',
            uploadDate: new Date().toISOString(),
            brickTypes: {
                regular: { count: 361, discount: '10%' },
                industrial: { count: 60, discount: '15%' },
                legendary: { count: 11, discount: '20%' }
            }
        };
        
        archive.append(JSON.stringify(collectionInfo, null, 2), { name: 'collection-info.json' });
        
        archive.finalize();
    });
}

// Function to upload zip file to Pinata
async function uploadZipToPinata(zipPath) {
    return new Promise((resolve, reject) => {
        const fileData = fs.readFileSync(zipPath);
        const boundary = '----WebKitFormBoundary' + Math.random().toString(16).substr(2, 9);
        
        let body = Buffer.alloc(0);
        
        // Add metadata
        const metadata = {
            name: 'MetaBricks-Collection',
            description: 'Complete MetaBricks NFT collection with randomized mystery strategy',
            keyvalues: {
                collection: 'MetaBricks',
                totalFiles: '432',
                strategy: 'Randomized Mystery',
                uploadDate: new Date().toISOString()
            }
        };
        
        // Add metadata
        body = Buffer.concat([body, Buffer.from(`--${boundary}\r\n`)]);
        body = Buffer.concat([body, Buffer.from('Content-Disposition: form-data; name="pinataMetadata"\r\n')]);
        body = Buffer.concat([body, Buffer.from('Content-Type: application/json\r\n\r\n')]);
        body = Buffer.concat([body, Buffer.from(JSON.stringify(metadata))]);
        body = Buffer.concat([body, Buffer.from('\r\n')]);
        
        // Add zip file
        body = Buffer.concat([body, Buffer.from(`--${boundary}\r\n`)]);
        body = Buffer.concat([body, Buffer.from('Content-Disposition: form-data; name="file"; filename="metabricks-collection.zip"\r\n')]);
        body = Buffer.concat([body, Buffer.from('Content-Type: application/zip\r\n\r\n')]);
        body = Buffer.concat([body, fileData]);
        body = Buffer.concat([body, Buffer.from('\r\n')]);
        
        // Add boundary end
        body = Buffer.concat([body, Buffer.from(`--${boundary}--\r\n`)]);
        
        const options = {
            hostname: 'api.pinata.cloud',
            port: 443,
            path: '/pinning/pinFileToIPFS',
            method: 'POST',
            headers: {
                'pinata_api_key': PINATA_CONFIG.apiKey,
                'pinata_secret_api_key': PINATA_CONFIG.secretKey,
                'Content-Type': `multipart/form-data; boundary=${boundary}`,
                'Content-Length': body.length
            }
        };
        
        const req = https.request(options, (res) => {
            let responseData = '';
            
            res.on('data', (chunk) => {
                responseData += chunk;
            });
            
            res.on('end', () => {
                try {
                    const parsed = JSON.parse(responseData);
                    if (res.statusCode === 200) {
                        resolve(parsed);
                    } else {
                        reject(new Error(`HTTP ${res.statusCode}: ${parsed.error || 'Unknown error'}`));
                    }
                } catch (e) {
                    reject(new Error(`Failed to parse response: ${responseData}`));
                }
            });
        });
        
        req.on('error', (error) => {
            reject(error);
        });
        
        req.write(body);
        req.end();
    });
}

// Main function
async function uploadMetaBricksZip() {
    try {
        console.log('🚀 Starting MetaBricks ZIP upload to Pinata...\n');
        console.log('📦 This will create a single ZIP file containing all 432 metadata files\n');
        console.log('🎲 Files will be organized in randomized order for mystery strategy\n');
        
        // Check if archiver is available
        try {
            require('archiver');
        } catch (error) {
            console.log('📦 Installing archiver package...');
            const { execSync } = require('child_process');
            execSync('npm install archiver', { stdio: 'inherit' });
        }
        
        // Create ZIP file
        console.log('📦 Creating MetaBricks collection ZIP file...\n');
        const zipPath = await createMetaBricksZip();
        
        // Upload ZIP to Pinata
        console.log('📤 Uploading ZIP file to Pinata...\n');
        const uploadResult = await uploadZipToPinata(zipPath);
        
        console.log('🎉 ZIP upload successful!\n');
        console.log('📊 Upload Results:');
        console.log(`   🔑 IPFS Hash: ${uploadResult.IpfsHash}`);
        console.log(`   📁 File Name: ${uploadResult.Name}`);
        console.log(`   📏 File Size: ${uploadResult.PinSize} bytes`);
        console.log(`   🕒 Timestamp: ${uploadResult.Timestamp}`);
        
        // Create access URL
        const zipUrl = `https://gateway.pinata.cloud/ipfs/${uploadResult.IpfsHash}`;
        console.log(`\n🔗 ZIP File URL: ${zipUrl}`);
        
        // Save upload results
        const resultsFile = path.join(__dirname, 'metabricks-zip-upload-results.json');
        const results = {
            uploadDate: new Date().toISOString(),
            ipfsHash: uploadResult.IpfsHash,
            fileName: uploadResult.Name,
            fileSize: uploadResult.PinSize,
            zipUrl: zipUrl,
            totalFiles: 432,
            strategy: 'Randomized Mystery'
        };
        
        await fs.writeFile(resultsFile, JSON.stringify(results, null, 2));
        console.log(`\n📝 Upload results saved to: ${resultsFile}`);
        
        // Show next steps
        console.log('\n🚀 Next Steps:');
        console.log('1. ✅ All MetaBricks metadata uploaded as single ZIP file');
        console.log('2. ✅ One IPFS hash for entire collection');
        console.log('3. ✅ Easy to download and extract');
        console.log('4. ✅ Use the ZIP URL for your MetaBricks configuration');
        console.log('5. ✅ Ready for NFT minting with mystery strategy!');
        
        console.log('\n💡 Benefits of this approach:');
        console.log('   • Single file instead of 432 scattered files');
        console.log('   • Easy to download and manage');
        console.log('   • Professional presentation');
        console.log('   • Can be extracted to access individual files');
        
        // Clean up local ZIP file
        await fs.remove(zipPath);
        console.log(`\n🧹 Local ZIP file cleaned up: ${zipPath}`);
        
    } catch (error) {
        console.error('❌ Error during ZIP upload:', error);
    }
}

// Run if executed directly
if (require.main === module) {
    uploadMetaBricksZip();
}

module.exports = {
    uploadMetaBricksZip,
    createMetaBricksZip
};
